name: form_builder_phone_field
description: International phone number field for FlutterFormBuilder package
version: 2.0.1
repository: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field
issue_tracker: https://github.com/flutter-form-builder-ecosystem/form_builder_phone_field/issues
homepage: https://github.com/flutter-form-builder-ecosystem
funding:
  - https://opencollective.com/flutter-form-builder-ecosystem

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=3.22.2"

dependencies:
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  phone_number: ^2.1.0
  country_pickers: ^3.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
